% function [Fh, Fd_On, Fd_Off, He_Off, Hi_Off, Ve_Off, Vi_Off] = emd(EMD_nx, EMD_ny, a_low, b_high, Fh_before, Fd_On_before, Fd_Off_before, picture, newpicture) % 原始的写法
function [Fh, Off, Fd_Off, He_Off, Hi_Off, Ve_Off, Vi_Off] = emd(EMD_nx, EMD_ny, a_low, b_high, Fh_before, Fd_Off_before, picture, newpicture) % ppxie修改之后的写法
%EMD Visual motion estimation by EMD array

Fh = zeros(EMD_nx+1, EMD_ny+1);          % signals generated by high-pass filtering（经过高通滤波器处理之后的矩阵结果）
Off = zeros(EMD_nx+1, EMD_ny+1);         % 前面经过高通滤波器处理之后，这里再经过OFF整流之后的矩阵结果
Fd_Off=zeros(EMD_nx+1, EMD_ny+1);        % low-pass filtering（经过OFF整流和低通滤波器处理之后的结果）

% % test
% imshow(uint8(newpicture));
% % imshow(newpicture);
% imshow(Fh);

%------------OFF pathway---------（注意：这里只有OFF整流，没有ON整流）
He_Off = zeros(EMD_nx, EMD_ny);           % the response in one arm of the motion detector（H是指horizontal水平的？）149×199
Hi_Off = zeros(EMD_nx, EMD_ny);           % the response in its mirror-symmetrical counterpart（镜像对称）
Ve_Off = zeros(EMD_nx, EMD_ny);           % the response in one arm of the motion detector（V是指vertical垂直的？）
Vi_Off = zeros(EMD_nx, EMD_ny);           % the response in its mirror-symmetrical counterpart

for i =1:(EMD_nx+1) % 1~150
    for j =1:(EMD_ny+1) % 1~200
        Fh(i, j) = b_high(1, 1)*(newpicture(i, j)-picture(i, j))+b_high(1, 2)*Fh_before(i, j);    % high-pass filtering
        Off(i, j) = OffRect(Fh(i, j), 0.05); % 前面经过高通滤波器处理过的信号，再经过Off整流之后的矩阵结果
%         Off(i, j) = OffRect(Fh(i, j), 0); % 把OFF的阈值由0.05改成0试试！
        Fd_Off(i, j) =a_low(1, 1)*Off(i, j)+a_low(1, 2)*Fd_Off_before(i, j);                      % low-pass filtering
    end
end

% % test
% imshow(uint8(newpicture));
% title('newpicture');
% 
% figure(2);
% % imshow(uint8(Fh)); % double to uint8
% imshow(Fh);
% title('Fh');
% 
% figure(3);
% % imshow(uint8(Off)); % double to uint8
% imshow(Off);
% title('Off');
% 
% figure(4);
% % imshow(uint8(Fd_Off)); % double to uint8
% imshow(Fd_Off);
% title('Fd_Off');

for i =1:EMD_nx % 1~149
    for j =1:EMD_ny % 1~199
        %------------OFF pathway---------
        He_Off(i, j)=Fd_Off(i, j)*Off(i, j+1); % 左->右时，He_Off(i,j)很大？右->左时，He_Off(i,j)为零？
        Hi_Off(i, j)=Off(i, j)*Fd_Off(i, j+1); % 左->右时，Hi_Off(i,j)为零？右->左时，Hi_Off(i,j)很大？
        
        Ve_Off(i, j)=Fd_Off(i, j)*Off(i+1, j); % 上->下时，Ve_Off(i,j)很大？下->上时，Ve_Off(i,j)为零？
        Vi_Off(i, j)=Off(i, j)*Fd_Off(i+1, j); % 上->下时，Vi_Off(i,j)为零？下->上时，Vi_Off(i,j)很大？
    end
end
end
