% 线条，显示横线
% 主要是确定线段的两个端点的坐标！

clc, clear, close all;

% 1、绘制（0，0）到（1，1）的实线段
hold on; % hold on是当前轴及图像保持而不被刷新，准备接受此后将绘制的图形，多图共存
annotation('line',[0 1],... % 两个元素的向量[x_begin x_end]，表示起始x坐标和结束x坐标。图窗的左下角映射到 (0,0)，右上角映射到 (1,1)。
    [0 1],...                 % 两个元素的向量[y_begin y_end]，表示起始y坐标和结束y坐标。图窗的左下角映射到 (0,0)，右上角映射到 (1,1)。
    'LineStyle','-',...                                     % Line style："-" (default) | "--" | ":" | "-." | "none"
    'LineWidth',6,...                                       %  Line width：0.5 (default) | positive value
    'Color',[0.501960813999176 0.501960813999176 0.501960813999176]); % Line color：[0 0 0] (default) | RGB triplet | hexadecimal color code | "r" | "g" | "b" | ...

% 2、绘制（0，0）到（0， 1）的黑色 虚线段
hold on;
annotation('line', [0, 0],...
    [0, 1],...
    'LineStyle','--',...
    'LineWidth',6,...
    'Color',[0, 0, 0]); % 黑色的RGB triplet为[0 0 0]

% 3、绘制（0，0）到（1，0）的红色 虚线段
hold on;
annotation('line', [0, 1],...
    [0, 0],...
    'LineStyle','--',...
    'LineWidth',6,...
    'Color',[1, 0, 0]); % 红色的RGB triplet为[1 0 0]

% 4、绘制（1，0）到（1，1）的绿色 实线段
hold on;
annotation('line', [1, 1],...
    [0, 1],...
    'LineStyle','-',...
    'LineWidth',6,...
    'Color',[0, 1, 0]); % 绿色的RGB triplet为[0 1 0]

% 5、绘制（0，1）到（1，1）的蓝色 实线段
hold on;
annotation('line', [0, 1],...
    [1, 1],...
    'LineStyle','-',...
    'LineWidth',6,...
    'Color',[0, 0, 1]); % 蓝色的RGB triplet为[0 0 1]

% 6、绘制（0，0.5）到（1，0.5）的黄色 虚线段
hold on;
annotation('line', [0, 1],...
    [0.5, 0.5],...
    'LineStyle','-',...
    'LineWidth',6,...
    'Color',[1, 1, 0]); % 黄色的RGB triplet为[1 1 0]
    

