function [Fh, Fd_On, Fd_Off, He_On, Hi_On, Ve_On, Vi_On, He_Off, Hi_Off, Ve_Off, Vi_Off] = emd(EMD_nx, EMD_ny, a_low, b_high, Fh_before, Fd_On_before, Fd_Off_before, picture, newpicture)
%EMD Visual motion estimation by EMD array
% EMD_nx, EMD_ny：EMD阵列的宽和高
% a_low, b_high：设置的低通滤波器的两个参数、高通滤波器的两个参数
% Fh_before, Fd_On_before,Fd_Off_before：预留的矩阵变量坑位，记录当前帧经过高通滤波器、ON整流及低通滤波器、OFF整流及低通滤波器处理之后的矩阵
% picture, newpicture：视频序列的当前帧和下一帧
%   Code written by Junyu Zhao.
%   December 20, 2022.

Fh = zeros(EMD_nx+1, EMD_ny+1);          % signals generated by high-pass filtering（当前帧经过高通滤波器之后的信号）

On = zeros(EMD_nx+1, EMD_ny+1); %（经高通滤波器处理之后，紧接着当前帧再经过ON整流器之后的信号）
Off = zeros(EMD_nx+1, EMD_ny+1); %（经高通滤波器处理之后，紧接着当前帧再经过OFF整流器之后的信号）
Fd_On=zeros(EMD_nx+1, EMD_ny+1);         % low-pass filtering（经ON整流器处理之后，紧接着当前帧再经低通滤波器之后的信号）
Fd_Off=zeros(EMD_nx+1, EMD_ny+1);        % low-pass filtering（经OFF整流器处理之后，紧接着当前帧再经低通滤波器之后的信号）

%------------ON pathway---------
He_On = zeros(EMD_nx, EMD_ny);           % the response in one arm of the motion detector
Hi_On = zeros(EMD_nx, EMD_ny);           % the response in its mirror-symmetrical counterpart
Ve_On = zeros(EMD_nx, EMD_ny);           % the response in one arm of the motion detector
Vi_On = zeros(EMD_nx, EMD_ny);           % the response in its mirror-symmetrical counterpart
%------------OFF pathway---------
He_Off = zeros(EMD_nx, EMD_ny);
Hi_Off = zeros(EMD_nx, EMD_ny);
Ve_Off = zeros(EMD_nx, EMD_ny);
Vi_Off = zeros(EMD_nx, EMD_ny);

for i =1:(EMD_nx+1) % 1~150
    for j =1:(EMD_ny+1) % 1~200
        Fh(i, j) = b_high(1, 1)*(newpicture(i, j)-picture(i, j))+b_high(1, 2)*Fh_before(i, j);    % high-pass filtering（高通滤波器处理）
        On(i, j) = OnRect(Fh(i, j), 0);      % ON整流器处理
        Off(i, j) = OffRect(Fh(i, j), 0.05); % OFF整流器处理
%         Off(i, j) = OffRect(Fh(i, j), 0); % OFF阈值由0.05改成0试试看！
        
        Fd_On(i, j) =a_low(1, 1)*On(i, j)+a_low(1, 2)*Fd_On_before(i, j);                         % low-pass filtering（ON整流器处理后的，再经低通滤波器处理）
        Fd_Off(i, j) =a_low(1, 1)*Off(i, j)+a_low(1, 2)*Fd_Off_before(i, j);                      % （OFF整流器处理后的，再经低通滤波器处理）
    end
end

for i =1:EMD_nx % 1~149
    for j =1:EMD_ny % 1~199
        %------------ON pathway---------
        He_On(i, j)=Fd_On(i, j)*On(i, j+1); % 水平的，ON的第一个M（向右）
        Hi_On(i, j)=On(i, j)*Fd_On(i, j+1); % 水平的，ON的第二个M（向左）
        
        Ve_On(i, j)=Fd_On(i, j)*On(i+1, j); % 垂直的，ON的第一个M（向下）
        Vi_On(i, j)=On(i, j)*Fd_On(i+1, j); % 垂直的，ON的第二个M（向上）
        
        %------------OFF pathway---------
        He_Off(i, j)=Fd_Off(i, j)*Off(i, j+1); % （向右）
        Hi_Off(i, j)=Off(i, j)*Fd_Off(i, j+1); % （向左）
        
        Ve_Off(i, j)=Fd_Off(i, j)*Off(i+1, j); % （向下）
        Vi_Off(i, j)=Off(i, j)*Fd_Off(i+1, j); % （向上）
    end
end
end
